name: jesseHarshbarger
favicon: null
layout_spectrum: 0.01464126375503838
typography_spectrum: 0.8770883847028017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6697930721566081
  lightness: 0.45666365302167833
  saturation: 0.5798067469149828
  rhythmicContrast: 0.9821408733259887
purpose: []
